### ISSUE TITLE
CMS page links with same url/identifier

### ISSUE THREAD

**Issue by nicolaisen** [SnowdogApps/magento2-menu#91] opened 2019-06-19 08:21 UTC
Issue when you have different websites/stores with different content, but the same url/identifier. It is only possible to choose the latest one.

**Comment by Igloczek** [comment] 2020-04-14 12:24
Thanks for pointing this out!
Fix for your issues is already released as version 2.11.0, hope it will help.

**Comment by besim-trellis** [comment] 2022-03-30 16:56
This issue seems to be happening on M2.4.3-p1 Cloud Commerce. Currently there are 3 stores, and selecting a CMS page which has same url as in another store, always chooses the last one.

**Comment by andrzejborkowski** [comment] 2022-04-07 06:33
Unfortunately we don't have such an env you pointed out, but I checked the issue with m2.4.2 and menu module v2.18.0 and wasn't able to replicate the issue. Could you please try to update you module version to the latest one?
![Screenshot 2022-04-07 at 08 29 42](https://user-images.githubusercontent.com/73829518/162134693-dfd8aac4-d3bc-4f9a-b54f-744c1d644498.png)

**Comment by besim-trellis** [comment] 2022-04-11 20:16
@andrzejborkowski It's happening with v2.18.0 too - the issue is with the selection, as we're able to see store information for each CMS page listed, but for pages with same url, the last page is always selected. Please check screen-recording below:

https://user-images.githubusercontent.com/56651164/162824214-61e4fae4-1c15-4320-80c9-516884ecac09.mp4

**Comment by andrzejborkowski** [comment] 2022-04-13 12:12
ok, thanks for the recording, now I can re-create the issue. I created an internal ticket DEV-88914 and our devs will take a look at the issue soon

**Comment by adamwaclawczyk** [comment] 2022-08-02 07:26
#245 merged to develop

**Closed** 2022-09-28 09:54 UTC
