### ISSUE TITLE
Error during menu export

### ISSUE THREAD

**Issue by Irinina** [SnowdogApps/magento2-menu#257] opened 2022-11-16 10:06 UTC
When trying to export the menu, we get the message `An error occurred while exporting menu 1.`. Error logs show:
```
report.CRITICAL: RuntimeException: Index invalid or out of range in www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export/Node/Tree.php:77
Stack trace:
#0 www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export/Node/Tree.php(71): Snowdog\Menu\Model\ImportExport\Processor\Export\Node\Tree->reindexTreeNodes(Array)
#1 www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export/Node/Tree.php(71): Snowdog\Menu\Model\ImportExport\Processor\Export\Node\Tree->reindexTreeNodes(Array)
#2 www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export/Node/Tree.php(55): Snowdog\Menu\Model\ImportExport\Processor\Export\Node\Tree->reindexTreeNodes(Array)
#3 www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export/Node.php(69): Snowdog\Menu\Model\ImportExport\Processor\Export\Node\Tree->get(Array)
#4 www.test.de/vendor/snowdog/module-menu/Model/ImportExport/Processor/Export.php(32): Snowdog\Menu\Model\ImportExport\Processor\Export\Node->getList(1)
#5 www.test.de/vendor/snowdog/module-menu/Controller/Adminhtml/Menu/Export.php(60): Snowdog\Menu\Model\ImportExport\Processor\Export->getExportData(1)
```
We are on Magento 2.4.5-p1, PHP 8.1. We suspect, that this might be caused by our menu entries containing umlauts (e.g. German ö), but just an idea.
![menu](https://user-images.githubusercontent.com/82020146/202151163-2fb7d422-4c2e-41a0-9e19-79962e66968b.png)

**Comment by andrzejborkowski** [comment] 2022-11-16 10:55
hi @Irinina 
I was trying to replicate this issue/error on our stage using german special letters, but it works as expected with m2.4.4 and menu module 2.20.0 (see attached screen). Probably it's due to our module wasn't tested on m2.4.5-p1 yet so it's not compatible with this new magento version. However, I created an internal ticket DEV-95193 to check it with our dev team 
![Screenshot 2022-11-16 at 11 38 27](https://user-images.githubusercontent.com/73829518/202161827-9b971c2f-8cc2-4f19-9c04-46f77f59bf05.png). I'll let you know if we'll find the reason.
Regards,
Andrzej

**Comment by andrzejborkowski** [comment] 2022-11-18 12:54
Hi @Irinina , below is feedback from our dev, could you please check it and provide more details, please?

I was able to reproduce this issue by manually corrupting the `position` data in `snowmenu_node` table. Umlauts are parsed correctly on fresh 2.4.5-p1, php8.1 Magento env.

I think we can try resolving this with a sanity check first.

```
SELECT
    *
FROM
    snowmenu_node
WHERE
    node_id IN(
    SELECT
        GROUP_CONCAT(node_id)
    FROM
        `snowmenu_node`
    GROUP BY
        parent_id
    HAVING
        COUNT(`snowmenu_node`.`node_id`) <= MAX(`snowmenu_node`.`position`)
)
```
This query should return nodes with incorrect `position` values. Changing their `position` to lower number than COUNT could fix this export problem.
If this doesn't show anything, we might need db dump of `snowmenu_node` table to further investigate this issue.

Could you also share more info on what was done in Admin Panel > Content > Elements > Menus? We would appreciate any info that would help with replicating the menu that's causing this problem. Thanks in advance!

**Comment by Irinina** [comment] 2022-11-22 12:29
Hello @andrzejborkowski, 
thank you very much for your fast answers and investigation.

What was done in Admin Panel > Content > Elements > Menus was to create the menu and then add some nodes, really nothing fancy or out of the normal.
But the query you gave me indeed returns one entry. As far as I see, in a submenu with three child nodes, the child nodes don't have positions 0,1,2 but 1,2,3. The query returns the one child node that has position 1. 
In all other submenus, the child nodes have positions starting with 0. 
I don't know if this is really the problem, and I can't explain how this can happen. It would be nice, if I could send you a dump of the `snowmenu_node` table. Maybe the devs see something that explains this behavior, so we might know for the future how to avoid this. Can you please tell me, where to send the db dumb (support email address or the like)?

Kind regards
Irina

**Comment by andrzejborkowski** [comment] 2022-12-02 06:29
Hi @Irinina,
we were trying to replicate the issue to get the incorrect nodes position, but all the time it works as intended and menu nodes have correct positions. It seems that this could be some specific issue of your project and the issue is not related to menu module logic, but as the last attempt, let's check your *snowmenu_* tables, you can attach it to this issue. Thanks!
Regards,
Andrzej

**Comment by andrzejborkowski** [comment] 2022-12-15 11:12
Hi @Irinina,
were you able to resolve the issue or would you like still to share your snowmenu_tables as was requested in the previous note? Or we can close this issue?

**Comment by Irinina** [comment] 2022-12-15 14:43
Hello @andrzejborkowski,
sorry for not coming back to you for a while. Meanwhile, our client has added more categories to the menu and I just tested it - the export works again! I don't know how adding more nodes could have fixed the broken positions of the old ones. But as I can't reproduce it anymore, I'd say, this issue can be closed.
Thank you for your fast and helpful support!

**Closed** 2022-12-15 14:44 UTC
