### ISSUE TITLE
[Vue warn]: Error in render: "TypeError: option.store.join is not a function"

### ISSUE THREAD

**Issue by FloriaanTickles** [SnowdogApps/magento2-menu#125] opened 2020-08-31 13:30 UTC
When adding a menu node with type "cms page link" while clicking on the page selector the following error occurs:

```
vue.js:634 [Vue warn]: Error in render: "TypeError: option.store.join is not a function" found in 
\<VSelect>
      \<AutoComplete>
         \<CmsPage>
           \<SnowdogMenuType>
             \<VddlNodrag>
               \<VddlList>
                 \<VddlDraggable>
                   \<List>
                     \<VddlList>
                       \<SnowdogMenu>
                         \<Root>
```

**Comment by Januszpl** [comment] 2020-09-14 12:41
Probably #127 - already merged into develop fixes it but I will verify it later.
Unless @FloriaanTickles you can check if latest develop fixes it?

**Comment by Januszpl** [comment] 2020-09-16 19:32
@FloriaanTickles could you provide more details?
Steps to reproduce? 
Do you have any CMS page defined?

**Comment by snowremi** [comment] 2020-09-29 09:40
We could not reproduce the error on our site, and we didn't receive any more details to reproduce the issue. I'm closing this issue. @FloriaanTickles, if you still experience the described error, please provide us more information. Thank you

**Closed by snowremi** 2020-09-29 09:40 UTC
