### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by bvboas** [SnowdogApps/magento2-menu#8] opened 2017-07-18 10:08 UTC
Changing from dev to production gives the following error:

```
PHP Fatal error:  Declaration of Snowdog\Menu\Block\NodeType\AbstractNode::getHtml() must be compatible with Snowdog\Menu\Api\NodeTypeInterface::getHtml(Snowdog\Menu\Api\int $nodeId, Snowdog\Menu\Api\int $level) in /home/user/public_html/app/code/Snowdog/Menu/Block/NodeType/AbstractNode.php on line 20
```

**Comment by dawiddczaja** [comment] 2017-07-25 14:27
Hello, I tried reproduce bug in CE and EE version but without effect. Which magento and magento2-menu version you have ?

**Comment by SilvanLaroo** [comment] 2017-07-26 14:05
Hi,

I'm facing the same issue. I'm using Magento 2.1.7 and the latest version of your extension.

**Comment by MskiPl** [comment] 2017-07-27 08:27
@bvboas @SilvanLaroo fixed on develop branch. Please test.

**Comment by SilvanLaroo** [comment] 2017-07-27 12:36
I've just installed the version from dev-develop, but got a similar error:
`Warning: Uncaught Exception: Warning: Declaration of Snowdog\Menu\Block\NodeType\Category\Interceptor::isCurrentCategory($nodeId) should be compatible with Snowdog\Menu\Block\NodeType\Category::isCurrentCategory(int $nodeId) in `

**Comment by MskiPl** [comment] 2017-07-27 13:14
@SilvanLaroo thanks but that's not directly related to this issue. I will open a separate issue for that.
Anyway please confirm the error reported here has been fixed, ok?

**Comment by SilvanLaroo** [comment] 2017-07-27 13:15
It's related right? The problem is that Magento does not include Scalar Type hinting in the var/generation files.

**Comment by MskiPl** [comment] 2017-07-27 13:27
That's right. Magento Team fixed it here https://github.com/magento/magento2/issues/6106 but it hasn't been merged into the master branch yet.
I created a separate task to remove all PHP7 type hints in our module: https://github.com/SnowdogApps/magento2-menu/issues/10

**Comment by mskipl** [comment] 2017-07-28 07:55
The fix has been merged into the develop branch (https://github.com/SnowdogApps/magento2-menu/commit/bd50cd2776af7336a701e5f907f7d2b642387271).

**Closed by mskipl** 2017-07-28 07:55 UTC
Labels: bug
