### ISSUE TITLE
Menu blocks are cached excessively 

### ISSUE THREAD

**Issue by dverkade** [SnowdogApps/magento2-menu#276] opened 2023-05-12 13:35 UTC
## Description

We're using this module for rending the menu of a store. Our monitoring alerts us for high usage of Redis cache. 

`WARNING: memory_utilization is 93.6851771543128 > 85 - REDIS 7.0.11 on XXXXX.creamcloud.io:6379 has 4 databases (db2, db3, db5, db0) with 1432760 keys, up 9 days 47 minutes - memory use is 8.93G (peak 11.79G, 93.69% of max, fragmentation 1.23%)`

Upon investigation this module seems to be the root cause of the issue as it's caching a large amount of blocks in Redis.  

## Actual behaviour

Menu has over 2 million of cached items in Redis.
![image](https://github.com/SnowdogApps/magento2-menu/assets/1058480/1b3adab8-4c90-406a-80c7-4cee41259ac2)

## Expected behaviour

Cache the rendered menu once and not as many times as it's being cached right now.

**Comment by jochhop** [comment] 2023-07-10 05:26
Hi @dverkade , thans again for opening the issue, we have spotted that this issue was caused by "current" menu node feature which was cached for each node, therefore we have removed that feature from backend side and developed it in frontend side instead.

The changes have been tested by our team and it seems all works fine keeping backward compatibility changes, so we have merged changes within develop branch and will build a new tag soon.

Have a great day,

Jose

**Closed by jochhop** 2023-07-10 05:26 UTC

**Comment by dverkade** [comment] 2023-08-18 07:08
Hi @jochhop,

When will this be released? I noticed the last release is from April, so this is not actually been released in a version yet.

Thanks!

**Comment by andrzejborkowski** [comment] 2023-08-18 07:17
Hi @dverkade

this has been released already on July 26 within [2.23.0](https://github.com/SnowdogApps/magento2-menu/tree/2.23.0) version

Regards,
Andrzej

**Comment by dverkade** [comment] 2023-08-18 07:20
@andrzejborkowski, thanks! 

I was looking here and the latest release is 2.21.0: https://github.com/SnowdogApps/magento2-menu/releases
